server:
  port: 9090

spring:
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: 123321
  redis:
    host: 192.168.187.101
    port: 6379
    database: 0
    timeout: 60000
    password: 123321
  mvc:
    hidden-method:
      filter:
        enabled: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_
      id-type: assign_uuid
      logic-delete-field: state
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.yefeng.boot_4.pojo
  mapper-locations: classpath:mappers/**/*.xml


